## NUMPY

__NumPy__ stands for Numerical Python and it's a fundamental package for scientific computing in Python. NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently. These lessons are intended as a basic overview of NumPy and introduce some of its most important features.

In the following lessons you will learn:

* How to import NumPy
* How to create multidimensional NumPy ndarrays using various methods
* How to access and change elements in ndarrays
* How to load and save ndarrays
* How to use slicing to select or change subsets of an ndarray
* Understand the difference between a view and a copy of an ndarray
* How to use Boolean indexing and set operations to select or change subsets of an ndarray
* How to sort ndarrays
* How to perform element-wise operations on ndarrays
* Understand how NumPy uses broadcasting to perform operations on ndarrays of different sizes.

* it is built on the language of c, which works at lower level of our computer

__Benefits of using NumPy__

Even though Python lists are great on their own, NumPy has a number of key features that give it great advantages over Python lists. Below are a few convincingly strong features:

* One such feature is speed. When performing operations on large arrays NumPy can often perform several orders of magnitude faster than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.

* Another great feature of NumPy is that it has multidimensional array data structures that can represent vectors and matrices. You will learn all about vectors and matrices in the Linear Algebra section of this course later on, and as you will soon see, a lot of machine learning algorithms rely on matrix operations. For example, when training a Neural Network, you often have to carry out many matrix multiplications. NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently, making it very suitable for solving machine learning problems.

* Another great advantage of NumPy over Python lists is that NumPy has a large number of optimized built-in mathematical functions. These functions allow you to do a variety of complex mathematical computations very fast and with very little code (avoiding the use of complicated loops) making your programs more readable and easier to understand.

These are just some of the key features that have made NumPy an essential package for scientific computing in Python. In fact, NumPy has become so popular that a lot of Python packages, such as Pandas, are built on top of NumPy.



In [2]:
import numpy as np
import time 

x = np.random.random(100000000)

# case 1 let's see plain python speed to calculate the mean 
start = time.time()
print(sum(x)/len(x))
print(time.time()-start)


#Let's see how much time it took for numpy 
start = time.time()
print(np.mean(x))
print(time.time()-start)

# Plain python toook 4 secs, numpy took 0.2 secs which is toooo much fast and efficient for large programs in our real life


0.5000011683459844
4.44094181060791
0.5000011683456965
0.018445730209350586


In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6])
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
x.dtype # in this case the array elements stored in signed int 64 bits, in numpy all elemets should of same type

dtype('int64')

In [4]:
x.shape # it gives the dimentions of the array

(6,)

In [5]:
Y = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) # creating 2 dimentional array
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
print(Y.shape) # 4 rows and 3 columns 

(4, 3)


In [7]:
print(Y.ndim) # this will print the total dimentions of the array 

2


In [9]:
print(Y.size) # this will print the total elements in the array 

12


In [6]:
# We can aslo create the arrays with the other data types like strings and float 

x = np.array(['Hello', 'World']) # now it's a array of words created by numpy array with elements of all the same datatype namely unicode strings of 5 characters
print(x)
print(x.shape)
x = np.array([1, 2, 'world'])
print(x)
print(x.shape)

['Hello' 'World']
(2,)
['1' '2' 'world']
(3,)


In [12]:
print(x.dtype) # it is stored in the data type of U5 string 

<U5


In [7]:
print(x)

['1' '2' 'world']


In [8]:
print(x.shape)

(3,)


In [9]:
print(type(x)) # still it is an array with the strins 

<class 'numpy.ndarray'>


In [10]:
# We can create the array with the multiple data types in the same array but the numpy will have to store everything in a same type 
# Even though the python had mixed datatypes, the array function created a numpy array with elements of all the same datatype namely unicode strings of 21 characters
x = np.array([1, 2, 'world'])

print(x)
print('shape :', x.shape)
print('type :', type(x))
print('dtype :', x.dtype)

['1' '2' 'world']
shape : (3,)
type : <class 'numpy.ndarray'>
dtype : <U21


### Unlike python list, the numpy array should contain all the elements of the same data type

* If we try to create multiple datatypes arrays then it will chooose one datatype for all the elements and create the np.array
* For suppose we create an array using the integers and floats then the numpy chooses the floats as the type and create the array, this is called the upcasting. this happens in order to loosing the precision in numarical computations
* Numpy aslo allows us to specify the perticular dtype while creating the array

* Once we 

In [18]:
x = np.array([1, 2.5, 4])
print(x.dtype) # will be of the float 

float64


In [21]:
x = np.array([1.5, 3.5, 55.7], dtype=np.int64) # Here we are specifying the dtype of the array 
print(x) # results integer values instead of the floats we defined in the definition
print(x.dtype)

[ 1  3 55]
int64


In [23]:
# We can also save the numpy array to the current directory as follows 

x = np.array([1, 2, 4, 3, 6, 3, 8, 20])
np.save('files/my_array', x)


In [25]:
# I can load my array as follows as per requirement 

y = np.load('files/my_array.npy')
print(y)

[ 1  2  4  3  6  3  8 20]


### Example 1.a - Using a 1-D Array of Integers (Rank #1 Array)


In [26]:
import numpy as np

# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


In [27]:
# We print information about x
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print('x has dimensions:', x.shape)
print('x has size:', x.size)

x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64
x has dimensions: (5,)
x has size: 5


### Example 1.b  - Using 1-D Array of Strings (Rank #1 Array)

In [28]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


### Example 1.c - Using a 1-D Array of Int and String (Rank #1 Array)
***NumPy will assign each element a same datatype because NumPy arrays must contains elements of same type.***

In [30]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape) 
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


### Example 1.d - Using a 1-D Array of Int and Float
***Upcasting demo*** - All integers will be converted (upgraded) to Float datatype. It is called upcasting, not downcasting, because a Float has a precision value (digits after the decimal). 

In [31]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


### Example 1.e - Using a 1-D Array of Float, and specifying the datatype of each element as int64
***NOTE*** - Precision will be lost in this example

In [32]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print the dtype x
print('x = ', x)
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
The elements in x are of type: int64


### Example 2 - Using a 2-D Array (Rank #2 Array)

In [33]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print information about Y
print('Y = \n', Y)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64
Y has dimensions: (4, 3)
Y has a total of 12 elements


### Example 3 - Save the NumPy array to a File

In [34]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('files/my_array', x)

In [35]:
# We load the saved array from our current directory into variable y
y = np.load('files/my_array.npy')

# We print information about the ndarray we loaded
print('Y = \n', y)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

Y = 
 [1 2 3 4 5]
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64


### Numpy Builtin Functions for creating arrays

so far we created the numpy arrays using the np.array() function, but we have so many other builtin functions to create in numpy as per our requirements

In [36]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
# can also specify the dtype while creating the array 

y = np.zeros((3,3), dtype=int)
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [39]:
x = np.ones((4,4), dtype= int)
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [40]:
x = np.ones((3,3)) # by default the dtype would be float

print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
# if we want to create the arrays with the constants then it is also possible in this numpy 

X = np.full((4, 3), 5) # (4, 3) is the shape, 5 is the constant that we want to create the array with, and the dtype would be the type of constant 
print(X)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [44]:
print(X.dtype)

int64


In [46]:
# Identity matrix is a square shape one which will have ones in the main diagonal and zeros everywhere else we can create this using eye()

I = np.eye(5,5) # we can also give single integer as an argument because it's square in shape
print(I)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [47]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
# we can also create customized diagonal matrix by defining the values 
X = np.diag([10, 20, 30, 40]) # the number of values here will be the shape of the matrix 
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [49]:
# np.arange() : it is just line range function we use for printing numbers, but here we use it to create arrays np.arange(start, stop, step)

X  = np.arange(10) # from 0 till 9
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
A = np.arange(1, 10) # from 1 to 9
print(A)

[1 2 3 4 5 6 7 8 9]


In [51]:
C = np.arange(5, 25, 3) # from 5 till 25 with step of 3
print(C)

[ 5  8 11 14 17 20 23]


In [53]:
# The arange function allows the floating point also as the step, but the result would be inconsistant because of inconsistant floating point precision so we use different function for this case

# x = np.linspace(start, stop, total_elements) start and stop are inclusive 

x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [55]:
# if u want the end_point to be exclusive then u can do that as follows 

d = np.linspace(1, 20, 10, endpoint=False)
print(d)

[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]


In [58]:
E = np.linspace(10, 40) # Here I did not mension the number of evenly spaced numbers so the it would take the default number which is 50
print(E)

[10.         10.6122449  11.2244898  11.83673469 12.44897959 13.06122449
 13.67346939 14.28571429 14.89795918 15.51020408 16.12244898 16.73469388
 17.34693878 17.95918367 18.57142857 19.18367347 19.79591837 20.40816327
 21.02040816 21.63265306 22.24489796 22.85714286 23.46938776 24.08163265
 24.69387755 25.30612245 25.91836735 26.53061224 27.14285714 27.75510204
 28.36734694 28.97959184 29.59183673 30.20408163 30.81632653 31.42857143
 32.04081633 32.65306122 33.26530612 33.87755102 34.48979592 35.10204082
 35.71428571 36.32653061 36.93877551 37.55102041 38.16326531 38.7755102
 39.3877551  40.        ]


In [59]:
# Now we have created so many single ranked arrays here in the above examples and now we can convert them into a specific shape using the reshape() functions

E =np.reshape(E, (5, 10))
print(E)

[[10.         10.6122449  11.2244898  11.83673469 12.44897959 13.06122449
  13.67346939 14.28571429 14.89795918 15.51020408]
 [16.12244898 16.73469388 17.34693878 17.95918367 18.57142857 19.18367347
  19.79591837 20.40816327 21.02040816 21.63265306]
 [22.24489796 22.85714286 23.46938776 24.08163265 24.69387755 25.30612245
  25.91836735 26.53061224 27.14285714 27.75510204]
 [28.36734694 28.97959184 29.59183673 30.20408163 30.81632653 31.42857143
  32.04081633 32.65306122 33.26530612 33.87755102]
 [34.48979592 35.10204082 35.71428571 36.32653061 36.93877551 37.55102041
  38.16326531 38.7755102  39.3877551  40.        ]]


In [63]:
F = np.arange(20)
print(F)

# Now let's convert the X into a rank 2 matrix
F = np.reshape(F, (4, 5))
print("Reshaped Array is : \n", F) 

# Note : for this to happen the total elemets in the array should be multple of the shape we decide

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array is : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [64]:
# we can directly use 2 functions in a single line unlike the above code

g = np.arange(20).reshape((4,5))
print(g)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [65]:
x = np.linspace(0, 50, 10, endpoint=False).reshape((2,5))
print(x)

[[ 0.  5. 10. 15. 20.]
 [25. 30. 35. 40. 45.]]


In [12]:
import numpy as np 

d= np.random.random((5,1))
print(d)

[[0.1723716 ]
 [0.75084579]
 [0.52747986]
 [0.12481851]
 [0.05226714]]


In [14]:
e= np.random.random(((1,5)))
print(e)

[[0.37313187 0.92393848 0.01812756 0.86557438 0.69573617]]


In [66]:
x = np.random.random((3, 3)) # Creates the matrix from 0, 1(exclusive) range 
print(x)

[[0.26666876 0.09482472 0.06822899]
 [0.56744069 0.34734859 0.20671172]
 [0.69032354 0.96403542 0.43277004]]


In [68]:
x = np.random.randint(4, 15, (3,2)) # randint(lowerbound, upperbound,(rows, columns))
print(x)

[[ 8 11]
 [ 8 14]
 [ 9 12]]


In [69]:
# We can also create arrays with satistical values of our requirements for example the mean should be 0 on an average which are drawn from probability distribution
X = np.random.normal(0, 0.1, size=(1000, 1000)) # normal(mean, std, size=(1000, 1000)
print(X)


[[ 1.35909304e-01  5.30590260e-02  3.00188252e-02 ...  2.27339067e-01
   1.83636625e-04  3.74612907e-03]
 [ 1.01884821e-02 -1.38785535e-01 -1.22334240e-01 ...  1.36954571e-01
   4.97640369e-02  1.55470724e-01]
 [-4.11823762e-02  4.49348792e-02  9.83900952e-02 ... -9.73955650e-02
   1.68641265e-01 -1.42421324e-01]
 ...
 [-1.53159909e-01  6.64638841e-02  2.88383097e-01 ...  6.17502170e-02
   6.38905730e-02 -1.74732864e-02]
 [-1.46977339e-02 -3.67056731e-02  5.41199599e-02 ... -8.27547666e-02
   3.13945830e-02  2.24267818e-01]
 [ 1.82253955e-01 -1.19048692e-01 -3.11950398e-03 ... -1.17018593e-01
  -2.08171210e-01  2.21033742e-01]]


In [70]:
print("Mean : ", X.mean())
print("Std : ", X.std())
print("Max : ", X.max())
print("Min : ", X.min())
print("# Positive : ", (X>0).sum())
print("# Negative : ", (X<0).sum())

Mean :  2.1396385038798347e-05
Std :  0.09999182911654225
Max :  0.48484622075490846
Min :  -0.47661360859787155
# Positive :  500213
# Negative :  499787


Using the NumPy functions you learned about on the previous page, create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive).

In [71]:
import numpy as np

# Replace None with appropriate code
X = np.arange(2, 34, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [75]:
# another way 

import numpy as np

X = np.linspace(2, 32, 16, dtype=int).reshape(4, 4) # int
X = np.linspace(2, 32, 16).reshape(4, 4) # float by default
print(X)

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]


#### Numpy Arrays are mutable, after creating the array you can modify the array as per your requirement
* It can be modified
* It can be sliced in many possible ways
* you can achieve any subcet you want in the array
* Elements can be accessed using indices
* you can also use the negative indices
* 


In [76]:
import numpy as np 

x = np.array([1, 2, 3, 4, 5, 6, 7])

print(x)



[1 2 3 4 5 6 7]


In [77]:
print("1st element : ", x[0])
print("2nd element : ", x[1])
print("5th element : ", x[4])

print("Last element : ", x[-1])
print("Second last element : ", x[-2])

1st element :  1
2nd element :  2
5th element :  5
Last element :  7
Second last element :  6


In [78]:
# modification of the array

x[3] = 30

print(x) # modified array

[ 1  2  3 30  5  6  7]


In [81]:
# Now let's see for the rank 2 array 
import numpy as np

X = np.arange(1, 10).reshape(3, 3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
print("Element at (0, 0) :", X[0, 0])
print("Element at (0, 1) :", X[0, 1])
print("Element at (2, 2) :", X[2, 2])

Element at (0, 0) : 1
Element at (0, 1) : 2
Element at (2, 2) : 9


In [83]:
# modification 

X[0, 0] = 100

print(X) # now modified

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0, 4]) # deletes the 2 elements from the list
print(x)

[1 2 3 4 5]
[2 3 4]


In [3]:
import numpy as np


Y = np.arange(1, 10).reshape(3, 3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
W = np.delete(Y, 0, axis=0) # axis 0 means rows, 0th row is being deleted
print('\n', W)


 [[4 5 6]
 [7 8 9]]


In [5]:
V = np.delete(Y, [0, 2], axis=1) # Colums means 0th and 2nd colums will be deleted
print('\n', V)


 [[2]
 [5]
 [8]]


In [6]:
x = np.array([1, 2, 3, 4, 5])
print(x)


[1 2 3 4 5]


In [7]:
x = np.append(x, 6)
print(x)

[1 2 3 4 5 6]


In [8]:
x = np.append(x, [6, 8, 7])
print(x)

[1 2 3 4 5 6 6 8 7]


In [9]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
W = np.append(Y, [[10, 11, 13]], axis=0)
print(W)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 13]]


In [11]:
Y = np.append(Y, [[1, 2, 3]], axis=0)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [12]:
V = np.append(Y, [[10], [11], [12], [13]], axis=1) # Appending entire column
print(V)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]
 [ 1  2  3 13]]


In [14]:
import numpy as np 

x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [17]:
# Insert functions 

x = np.insert(x, 2, [9, 10]) # at position 2 the values 9 and 10 will be inserted and remaining will be adjusted 
print(x)

[ 1  2  9 10  9 10  3  4  5]


In [19]:
x = x.reshape(3, 3)
print(x)

[[ 1  2  9]
 [10  9 10]
 [ 3  4  5]]


In [2]:
import numpy as np 

Y = np.array([[1, 2, 3], [7, 8, 9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [3]:
W = np.insert(Y, 1, [4, 5, 6], axis=0)
print(W)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Let's insert a column with full of fives as below 

V = np.insert(W, 1, 5, axis=1) # W array, 1st column, value to be inserted, row or column
print(V)

[[1 5 2 3]
 [4 5 5 6]
 [7 5 8 9]]


In [8]:
# Let's insert a row with full of fives as below

W = np.insert(V, 1, 5, axis=0) # W array, 1st column, value to be inserted, row or column
print(W)

[[1 5 2 3]
 [5 5 5 5]
 [4 5 5 6]
 [7 5 8 9]]


#### Stacking the Numpy arrays 

* Vertical Stack : vstack()
* Horiozontal Stack : hstack()

* To stack the arrays the shape of the arrays must match 

In [9]:
import numpy as np 

x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [10]:
y = np.array([[4, 5, 6], [7, 8, 9]])
print(y)

[[4 5 6]
 [7 8 9]]


In [11]:
z = np.vstack((x, y))
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
a = np.vstack((y, y))
print(a)

[[4 5 6]
 [7 8 9]
 [4 5 6]
 [7 8 9]]


In [13]:
b = np.array([1,  2, 3])
c = np.array([[6, 7, 8],[9, 10, 11], [12, 13, 14]])

print(b)
print(c)

[1 2 3]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [15]:
w = np.hstack((c, b.reshape(3, 1)))
print(w)

[[ 6  7  8  1]
 [ 9 10 11  2]
 [12 13 14  3]]


In [16]:
f = np.array([1, 3, 4, 5])
c = np.array([[6, 7, 8, 1],[9, 10, 11, 2], [12, 13, 14, 4]])
g = np.vstack((c, f))
g

array([[ 6,  7,  8,  1],
       [ 9, 10, 11,  2],
       [12, 13, 14,  4],
       [ 1,  3,  4,  5]])