### SLICING NDARRAYS

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

    * The starting index is always included and end index is always excluded
    * numpy arrays cab be multidimentional so when slicing it's mandatory to mention size of each dimention of the array 

In [1]:
# Let's see some examples for rank 2 arrays 
import numpy as np

X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
# Imagine I want the last 9 values in the array as 3 by 3
# Remember that the indexing always starts with 0

#One way 
z = X[1:4, 2:5] # X[start_range:end_range for rows, start_range:endrange for columns] here also the starting index is included and end is excluded
print(z)


[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [7]:
# Another way 
y = X[1: , 2: ]
print(y)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [8]:
# Now imagine we need right top 3 by 3 from X

a = X[0:3, 2:5] # or X[:3, 2:]
print(a)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [10]:
b = X[2, : ] # selecting all elements from 3rd row
print(b)

[11 12 13 14 15]


In [11]:
c = X[:, 2] # All the rows from column 2
print(c)

# But it returns as rank 1 arraay 

[ 3  8 13 18]


In [12]:
# If you want rank 2 array then do as folollows 
d = X[:, 2:3]
print(d)

[[ 3]
 [ 8]
 [13]
 [18]]


In [13]:
print(X) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [14]:
z = X[1: , 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [15]:
z[2,2] = 555
print(z) # now what ever we change in z, all changes do reflect in the X main arrays also

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [16]:
print(X)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [17]:
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [18]:
z = np.copy(X[1:, 2:])
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [20]:
z[2, 2] = 555 # here we can seee that the X main array will not gte affected by the chnages in z as we copied that seperatly from the X
print(z)
print(X)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [22]:
y = X[indices, :]
print(y) # it means it will print 1 and 3 rows, and 2nd row willl not be included, all columns will be included

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [24]:
z = X[:, indices] # all rows but 1st and 3rd columns
print(z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [26]:
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [25]:
z = np.diag(X) # will return the diagonal elements of the X
print(z)

[ 0  6 12 18]


In [27]:
z = np.diag(X, k=1) # above the diagonal, by default k = 0 which is main diagonal 
print(z)

[ 1  7 13 19]


In [28]:
z = np.diag(X, k=-1) # below the diagonal
print(z)

[ 5 11 17]


In [29]:
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
print(X)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [30]:
print(np.unique(X)) # will print all the unique elements in the entire array 

[1 2 3 5 8]


### Boolean Indexing, set operations and sorting 

Up to now we have seen how to make slices and select elements of an ndarray using indices. This is useful when we know the exact indices of the elements we want to select. However, there are many situations in which we don't know the indices of the elements we want to select. For example, suppose we have a 10,000 x 10,000 ndarray of random integers ranging from 1 to 15,000 and we only want to select those integers that are less than 20. Boolean indexing can help us in these cases, by allowing us select elements using logical arguments instead of explicit indices. Let's see some examples:

In [32]:
import numpy as np

In [33]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [35]:
print(X[X>10]) # print all the elements > 10 in the X array

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [36]:
print(X[X<=7])


[0 1 2 3 4 5 6 7]


In [38]:
print(X[(X>10) & (X<17)])

[11 12 13 14 15 16]


In [40]:
X[(X>10) & (X<17)]= -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [41]:
# Set operations 

x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [45]:
# Sorting the arrays 

x = np.random.randint(1, 11, size=(10,))
print(x)

[ 1  9  5  4  8 10  2  9  3  2]


In [46]:
print(np.sort(x))

[ 1  2  2  3  4  5  8  9  9 10]


In [47]:
print(np.sort(np.unique(x))) # it won't change the original array 

[ 1  2  3  4  5  8  9 10]


In [48]:
print(x)

[ 1  9  5  4  8 10  2  9  3  2]


In [50]:
x.sort() # it wil change the original array
print(x)

[ 1  2  2  3  4  5  8  9  9 10]


In [51]:
# We can also sort by rows and columns also 

X = np.random.randint(1, 11, size=(5, 5))
print(X)

[[ 6  3  5  5  2]
 [ 3  1  3  8  4]
 [ 4  1 10  7  6]
 [ 6  1  3 10  7]
 [ 5  2  5 10  1]]


In [52]:
print(np.sort(X, axis=0)) # will be sorted by rows

[[ 3  1  3  5  1]
 [ 4  1  3  7  2]
 [ 5  1  5  8  4]
 [ 6  2  5 10  6]
 [ 6  3 10 10  7]]


print(np.sort(X, axis=1)) # will be sorted by columns 

Create a 5 x 5 ndarray X with consecutive integers from 1 to 25 (inclusive). Afterwards use Boolean indexing to pick out only the odd numbers in the array and assign the result to Y.

In [ ]:
import numpy as np

# TODO: replace None with appropriate code
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5,5)
print(X)

# TODO: replace None with appropriate code
# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X%2!=0]
print(Y)

### Arithmetic operations and Broadcasting


Use Broadcasting to create a 4 x 4 ndarray that has its first column full of `1`s, its second column full of `2`s, its third column full of `3`s, etc..

In [57]:
import numpy as np 

X = np.ones((4,4)) * np.arange(1,5)
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [ ]:
'''Explanation
np.ones((4,4)) will give you a 4 x 4 matrix:

[[1. 1. 1. 1.],
 [1. 1. 1. 1.],
 [1. 1. 1. 1.],
 [1. 1. 1. 1.]]
np.arange(1,5) will give you a 1 x 4 matrix:

[1 2 3 4]
X can be calculated by multiplying the above two matrices to get:

[[1. 2. 3. 4.],
 [1. 2. 3. 4.],
 [1. 2. 3. 4.],
 [1. 2. 3. 4.]]'''

## Glossary

### Category: General Purpose
| Function/Method                        | Description                                                                                                 |
|----------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `numpy.ndarray.dtype`                  | Return the data-type of the elements of the array. Remember, arrays are homogeneous.                        |
| `numpy.ndarray.ndim`                   | Return the number of array-dimensions (rank), e.g., it will return 2 for a 4x3 array.                       |
| `numpy.ndarray.shape`                  | Return a tuple representing the array dimensions, e.g., it will return (rows, columns) for a rank 2 array.  |
| `numpy.ndarray.size`                   | Return the number of elements present in the array.                                                         |
| `numpy.save`                           | Save an array to .npy (numpy) format.                                                                       |
| `numpy.load`                           | Load array from the .npy files.                                                                             |
| `numpy.random.random`                  | Return random floats values from the interval [0.0, 1.0), in a specified shape.                             |
| `numpy.random.randint`                 | Return random integers from the half-open interval [a, b), in a specified shape.                            |
| `numpy.random.normal`                  | Return random samples from a Gaussian (normal) distribution.                                                |
| `numpy.random.permutation`             | Return a randomly permuted sequence from the given list.                                                    |
| `numpy.reshape`                        | Returns an array containing the same elements with a new shape, without affecting the original array.       |
| `numpy.ndarray.reshape`                | Returns an array containing the same elements with a new shape, without affecting the original array.       |

### Category: Array Creation
| Function/Method                        | Description                                                                                                 |
|----------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `numpy.ones`                           | Return a new array of given shape and type, filled with 1s.                                                 |
| `numpy.zeros`                          | Return a new array of given shape and type, filled with 0s.                                                 |
| `numpy.full`                           | Return a new array of given shape and type, filled with a specific value.                                   |
| `numpy.eye`                            | Return a 2-D array with 1s on the diagonal and 0s elsewhere.                                                |
| `numpy.diag`                           | Extract the diagonal elements.                                                                              |
| `numpy.unique`                         | Return the sorted unique elements of an array.                                                              |
| `numpy.array`                          | Create an n-dimensional array.                                                                              |
| `numpy.arange`                         | Return evenly spaced values within a given half-open interval [a, b).                                       |
| `numpy.linspace`                       | Return evenly spaced numbers over a specified interval [a, b].                                              |
| `numpy.ndarray.copy`                   | Returns a copy of the array.                                                                                |

### Category: Operating with Elements and Indices
| Function/Method                        | Description                                                                                                 |
|----------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `numpy.insert`                         | Insert values along the given axis before the specified indices.                                            |
| `numpy.delete`                         | Return a new array, after deleting sub-arrays along a specified axis.                                       |
| `numpy.append`                         | Append values at the end of the specified array.                                                            |
| `numpy.hstack`                         | Return a stacked array formed by stacking the given arrays in sequence horizontally (column-wise).          |
| `numpy.vstack`                         | Return a stacked array formed by stacking the given arrays, will be at least 2-D, in sequence vertically (row-wise). |
| `numpy.sort`                           | Return a sorted copy of an array.                                                                           |
| `numpy.ndarray.sort`                   | Sort an array in-place.                                                                                     |

### Category: Set Operations
| Function/Method                        | Description                                                                                                 |
|----------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `numpy.intersect1d`                    | Find the intersection of two arrays.                                                                        |
| `numpy.setdiff1d`                      | Find the set difference of two arrays.                                                                      |
| `numpy.union1d`                        | Return the unique, sorted array of values that are in either of the two input arrays.                       |

### Category: Arithmetic and Statistical Operations
| Function/Method                        | Description                                                                                                 |
|----------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `numpy.add`                            | Element-wise add given arrays.                                                                              |
| `numpy.subtract`                       | Subtract arguments of given arrays, element-wise.                                                           |
| `numpy.multiply`                       | Multiply arguments of given arrays, element-wise.                                                           |
| `numpy.divide`                         | Returns a true division of the inputs, element-wise.                                                        |
| `numpy.exp`                            | Calculate the exponential of all elements in the input array.                                               |
| `numpy.power`                          | First array elements raised to powers from second array, element-wise.                                      |
| `numpy.sqrt`                           | Return the non-negative square-root of an array, element-wise.                                              |
| `numpy.ndarray.min`                    | Return the minimum along the specified axis.                                                                |
| `numpy.ndarray.max`                    | Return the maximum along a given axis.                                                                      |
| `numpy.mean`                           | Compute the arithmetic mean along the specified axis.                                                       |
| `numpy.ndarray.mean`                   | Compute the arithmetic mean along the specified axis.                                                       |
| `numpy.median`                         | Compute the median along the specified axis.                                                                |
